### ISSUE TITLE
Unable to Form Network with znp_CC1352P_2_LAUNCHXL_tirtos_ticlang_HFC.hex

### ISSUE THREAD

**Issue by shackrat** [verjus/Zigbee-3.0-USB-dongle-plus-firmware#2]
Interesting observation..  I have a couple extra Dongle-P adapters for testing.  I flashed znp_CC1352P_2_LAUNCHXL_tirtos_ticlang_HFC.hex for testing Hardware Flow Control.  No matter what I tried, or which adapter I used I was not able to form a new network using this image. 

Here are the startup errors:

```
zigbee2mqtt_test_ch14  | Using '/app/data' as data directory
zigbee2mqtt_test_ch14  | Zigbee2MQTT:debug 2023-01-23 12:51:18: Loaded state from file /app/data/state.json
zigbee2mqtt_test_ch14  | Zigbee2MQTT:info  2023-01-23 12:51:18: Logging to console and directory: '/app/data/log/2023-01-23.12-51-18' filename: log.txt
zigbee2mqtt_test_ch14  | Zigbee2MQTT:info  2023-01-23 12:51:18: Starting Zigbee2MQTT version 1.29.2 (commit #bb3e8f6)
zigbee2mqtt_test_ch14  | Zigbee2MQTT:info  2023-01-23 12:51:18: Starting zigbee-herdsman (0.14.83-hotfix.0)
zigbee2mqtt_test_ch14  | Zigbee2MQTT:debug 2023-01-23 12:51:18: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[14],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"zstack","path":"/dev/dongle-p","rtscts":true}}'
zigbee2mqtt_test_ch14  | Zigbee2MQTT:error 2023-01-23 12:51:55: Error while starting zigbee-herdsman
zigbee2mqtt_test_ch14  | Zigbee2MQTT:error 2023-01-23 12:51:55: Failed to start zigbee
zigbee2mqtt_test_ch14  | Zigbee2MQTT:error 2023-01-23 12:51:55: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
zigbee2mqtt_test_ch14  | Zigbee2MQTT:error 2023-01-23 12:51:55: Exiting...
zigbee2mqtt_test_ch14  | Zigbee2MQTT:error 2023-01-23 12:51:55: Error: network commissioning failed - timed out waiting for nib to settle
zigbee2mqtt_test_ch14  |     at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:364:19)
zigbee2mqtt_test_ch14  |     at ZnpAdapterManager.beginRestore (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:296:9)
zigbee2mqtt_test_ch14  |     at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:80:17)
zigbee2mqtt_test_ch14  |     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
zigbee2mqtt_test_ch14  |     at Zigbee.start (/app/lib/zigbee.ts:58:27)
zigbee2mqtt_test_ch14  |     at Controller.start (/app/lib/controller.ts:101:27)
zigbee2mqtt_test_ch14  |     at start (/app/index.js:107:5)
```

Yet, oddly I built my own image using your diff files and was able to successfully start Z2M and form a new network.
Not sure what the difference would be.  Just wanted to open an issue in case anyone runs into this.

**Comment by verjus** [comment]
This firmware has an issue that I and others have experienced. When z2m is restarted, it is often necessary to unplug and re-plug the USB dongle, before restarting z2m. Otherwise, all these weird errors appear. I don't know if that's related to the HFC modification or not. So, it could be that you didn't have to rebuild the firmware and a re-plug would have done the trick. See if your version works better and doesn't require the re-plug, I might have overlooked something.

**Comment by shackrat** [comment]
I flashed your file and put it right into the rPi to spin up a new instance.  I flashed mine and followed the same steps.  Mine came right up.  I don't think its anything you overlooked.  The only thing I can think of, is that I had to manually edit the znp.syscfg because I couldn't apply koenkk's patch. 

` * @versions {"tool":"1.12.0+2376"}`

The patch is looking for 

` * @versions {"tool":"1.12.0+2406"}`

That was the only deviation from the steps

I'm going to do some more testing and see how things go.  I'm having adapter crashing every couple days on a large network, so I am hopeful that flow control may help.

**Comment by shackrat** [comment]
I successfully tested my build for 24 hours on my small 3 device test network without any issues.  I proceeded to flash both of my production adapters with the build and both have been running for 16 hours without any issue so far.

I did not have any issue with the adapters not coming up after restarting Z2M several times.  I did see similar phenomenon using 20220219 where I would have to stop and restart the container.  Interestingly, I ran a checksum from my build and yours and both have different MD5 signatures.

My build is [posted here](https://github.com/shackrat/Sonoff-ZBDongle-Plus-Zigbee-3.0-Firmware) along with a couple steps I had to deviate from, if you wish to test.

**Comment by verjus** [comment]
Sounds good. I definitely will, since having to unplug the USB is a pain. BTW, are you sure we're talking about the same development version of Koenk's firmware? The one I [used](https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/firmware.patch) is referencing  `@versions {"tool":"1.14.0+2667"} `and not  `* @versions {"tool":"1.12.0+2376"}`

**Comment by shackrat** [comment]
That might be the difference.  I'm building 6.10.01 for Hardware Flow Control..  It seems to be quite stable.
The one you are referencing is 6.30.00.84, and it uses the new UART2 driver and rtos7.  I suspect that might be one of issues with the build.

FWIW..  There's a newer 6.40 SDK out there.  The patch doesn't seem to want to apply to it.  I may have to fiddle.

**Comment by shackrat** [comment]
I just built and tested SDK 6.40.00.13 both with and without hardware flow control.  You can find it in the [dev branch](https://github.com/shackrat/Sonoff-ZBDongle-Plus-Zigbee-3.0-Firmware/tree/sdk_6_40_00_13) in my repo.  I was able to flash my dev stick from 6.10 to 6.40 and have it startup without any need to unplug the stick, and was able to use the existing network.  I was also able to form a new network without any NIB errors with this build.  Going to run it for a day or to in my lab mesh then will try to deploy on one of my production meshes.

**Comment by verjus** [comment]
Perfect. Hopefully you can take over future builds from me as I have a very old PC and limited time.

**Comment by shackrat** [comment]
That composer studio is a pig.  It's slow as molasses on my 2021 MacBook Pro.  I can only imagine.  Time is not on my side either, although I'm happy too push a new build out now and then.  Let me know how your testing goes.
